//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobrinSerovControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directions
    {
        public Directions()
        {
            this.Activity = new HashSet<Activity>();
            this.Journal = new HashSet<Journal>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<Journal> Journal { get; set; }
    }
}
